# -*- coding: utf-8 -*-
"""webScrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BQhucI9T6bXE1_i0IdHboKzMPBRgwrfE
"""


import mechanicalsoup

browser = mechanicalsoup.StatefulBrowser()
url = "http://14.139.108.229/W27/login.aspx"

browser.open(url)
print(browser.get_url())

browser.get_current_page()

browser.select_form()
browser.get_current_form().print_summary()

browser["txtUserName"] = 21185
browser["Password1"] = "MEMBER"

response = browser.submit_selected()
print(response.text)

new_url ="http://14.139.108.229/W27/MyInfo/w27MyInfo.aspx"
browser.open(new_url)

page = browser.get_current_page()
# print(page)
table = page.find_all('table', attrs={"id" : "ctl00_ContentPlaceHolder1_CtlMyLoans1_grdLoans"})

table

if table:
  tds = table[0].find_all("td")
  book_data= []
  for td in tds:
    book_data.append(td.text.replace("\n",""))

  print(book_data)
  no_of_book_issued = int(len(book_data)/9)
  print(no_of_book_issued)

import pandas as pd

num_columns = 9
data_rows = [book_data[i:i+num_columns] for i in range(0, len(book_data), num_columns)]

# Create a DataFrame using pandas
columns = ['AccNum', 'Title', 'Author', 'Borrowed On', 'Due On', 'Status', 'Recalled', 'FineDue', 'Reissue']
df = pd.DataFrame(data_rows, columns=columns)

# Print the DataFrame
df

# print(tds)
reissue_btns = table[0].find_all("input")
issue_book_btn = []
for btn in reissue_btns:
  issue_book_btn.append(btn.attrs["id"])

issue_book_btn

df["Reissue"] = issue_book_btn
df

print(browser.select_form('#ctl00_ContentPlaceHolder1_CtlMyLoans1_grdLoans_ctl02_Button1'))

from datetime import datetime
import pytz

indian_time_zone = pytz.timezone('Asia/Kolkata')

# Get the current date and time in the Indian time zone
indian_current_datetime = datetime.now(indian_time_zone)

indian_current_datetime = datetime.now(indian_time_zone)
indian_current_date = indian_current_datetime.date()

for index, row in df.iterrows():
    due_date_str = row['Due On']
    due_date = datetime.strptime(due_date_str.strip(), "%d-%b-%Y").date()

    if due_date < indian_current_date:
        print(f"Due date for {row['Title']} has passed.")    
    elif due_date == indian_current_date:
        print(f"Today is the due date for {row['Title']}.")
    else:
        print(f"Due date for {row['Title']} is in the future.")